modLoader="javafml"
loaderVersion="[47,)"
license="GPLv3"

[[mods]]
modId="fissionrecipe"
version="3.0.3"
displayName="Mekanism Fission Recipe"
updateJSONURL="https://github.com/North-West-Wind/MekanismFissionRecipe/raw/main/update.json"
credits="Thanks to Mekanism for creating amazing contents"
logoFile="fissionrecipe.png"
authors="NorthWestWind"
description='''
Adds recipe support for Mekanism Fission Generator

Code extracted from Sky Farm
'''

[[dependencies.fissionrecipe]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fissionrecipe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fissionrecipe]]
    modId="mekanismgenerators"
    mandatory=true
    versionRange="[10.4.9,)"
    ordering="NONE"
    side="BOTH"
