modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://github.com/North-West-Wind/MekanismFissionRecipe/raw/main/update.json"
credits="Thanks to Mekanism for creating amazing contents"
logoFile="fissionrecipe.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${loader_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanismgenerators"
    mandatory=true
    versionRange="${mekanism_version_range}"
    ordering="NONE"
    side="BOTH"
