modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"

[[mods]]
modId="fissionrecipe"
version="1.0.0"
displayName="Mekanism Fission Recipe"
updateJSONURL="https://github.com/North-West-Wind/MekanismFissionRecipe/raw/main/update.json"
credits="Thanks to Mekanism for creating amazing contents"
logoFile="fissionrecipe.png"
authors="NorthWestWind"
description='''
Adds recipe support for Mekanism Fission Generator

Code extracted from Sky Farm
'''

[[dependencies.fissionrecipe]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fissionrecipe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fissionrecipe]]
    modId="mekanismgenerators"
    mandatory=true
    versionRange="[10,)"
    ordering="NONE"
    side="BOTH"
